insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 1,'Eula','Lane','eula.lane@jigrormo.ye','(762) 526-5961','1953-09-19','Insurance Clerk','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 2,'Barry','Rodriquez','barry.rodriquez@zun.mm','(267) 955-5124','2012-09-19','Mortarman','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 3,'Eugenia','Selvi','eugenia.selvi@capfad.vn','(680) 368-2192','1972-09-04','Beer Coil Cleaner','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 4,'Alejandro','Miles','alejandro.miles@dec.bn','(281) 301-2039','2012-10-22','Scale Attendant','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 5,'Cora','Tesi','cora.tesi@bivo.yt','(600) 616-7955','1970-12-20','Clinical Audiologist','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 6,'Marguerite','Ishii','marguerite.ishii@judbilo.gn','(882) 813-1374','1936-09-16','Parking Meter Collector','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 7,'Mildred','Jacobs','mildred.jacobs@joraf.wf','(642) 665-1763','1966-04-21','Business Unit Manager','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 8,'Gene','Goodman','gene.goodman@kem.tl','(383) 458-2132','2009-03-01','Technical Communicator','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 9,'Lettie','Bennett','lettie.bennett@odeter.bb','(769) 335-6771','1958-05-06','Correctional Officer Sergeant','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 10,'Mabel','Leach','mabel.leach@lisohuje.vi','(803) 586-8035','1945-04-12','Food Chemist','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 11,'Jordan','Miccinesi','jordan.miccinesi@duod.gy','(531) 919-2280','1981-05-24','Signals Intelligence/Electronic Warfare Chief','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 12,'Marie','Parkes','marie.parkes@nowufpus.ph','(814) 667-8937','1942-03-25','Language Pathologist','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 13,'Rose','Gray','rose.gray@kagu.hr','(713) 311-8766','1957-03-24','Wildlife Officer','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 14,'Garrett','Stokes','garrett.stokes@fef.bg','(381) 421-2371','2008-01-03','Bindery Machine Operator','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 15,'Barbara','Matthieu','barbara.matthieu@derwogi.jm','(940) 463-7299','1928-12-29','Instructional Aide','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 16,'Jean','Rhodes','jean.rhodes@wehovuce.gu','(777) 435-9570','1948-06-07','Clinical Psychiatrist','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 17,'Jack','Romoli','jack.romoli@zamum.bw','(517) 393-9630','1974-04-03','Mortician Investigator','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 18,'Pearl','Holden','pearl.holden@dunebuh.cr','(711) 904-3669','1948-07-29','Rod Buster Helper','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 19,'Belle','Montero','belle.montero@repiwid.si','(935) 404-4792','1931-08-22','Classroom Aide','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 20,'Olive','Molina','olive.molina@razuppa.ga','(935) 267-8492','1933-03-03','Traditional Chinese Herbalist','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 21,'Minerva','Todd','minerva.todd@kulmenim.ad','(763) 948-4815','1949-08-04','Electronic Drafter','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 22,'Bobby','Pearson','bobby.pearson@ib.kg','(238) 240-2561','2013-12-27','Vault Teller','Worker',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 23,'Larry','Ciappi','larry.ciappi@ba.lk','(410) 257-1723','1995-01-12','Fire Sprinkler Installer','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 24,'Ronnie','Salucci','ronnie.salucci@tohhij.lv','(566) 726-3346','1973-07-16','Brewery Pumper','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 25,'Walter','Grossi','walter.grossi@tuvo.sa','(416) 906-7221','1986-09-03','Kitchen Chef','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 26,'Frances','Koopmans','frances.koopmans@foga.tw','(611) 712-1562','1965-10-25','Medical Esthetician','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 27,'Frances','Fujimoto','frances.fujimoto@uswuzzub.jp','(919) 887-8542','1935-03-31','Auto Tire Worker','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 28,'Olivia','Vidal','olivia.vidal@hivwerip.vc','(982) 684-7650','1932-07-08','Semi-Truck Driver','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 29,'Edna','Henry','edna.henry@gugusu.rw','(811) 931-8202','1946-05-22','Command And Control','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 30,'Lydia','Brun','lydia.brun@zedekak.md','(927) 400-3928','1928-07-04','Drywall Hanger','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 31,'Jay','Blake','jay.blake@ral.mk','(365) 345-1498','2008-07-22','Real Property Evaluator','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 32,'Isabel','Serafini','isabel.serafini@turuhu.bh','(656) 968-9869','1972-07-30','Human Performance Professor','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 33,'Rebecca','Carter','rebecca.carter@omjo.et','(739) 612-6585','1958-02-16','V/Stol Landing Signal Officer','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 34,'Maurice','Fabbrini','maurice.fabbrini@rig.bh','(485) 521-2687','1991-12-23','Air Control/Anti-Air Warfare Officer','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 35,'Ollie','Turnbull','ollie.turnbull@sicewap.org','(835) 620-3330','1943-08-19','General Superintendent','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 36,'Jerry','Hopkins','jerry.hopkins@fo.mh','(211) 851-5960','2013-09-12','Child Protective Services Social Worker','External',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 37,'Nora','Lyons','nora.lyons@gegijap.na','(811) 311-5257','1944-06-26','Lens Grinder and Polisher','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 38,'Anne','Weiß','anne.weiß@kuvesa.pe','(843) 836-3759','1940-01-13','Civil Engineering Professor','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 39,'Louise','Gauthier','louise.gauthier@lapahu.mt','(913) 235-1856','1929-04-24','Mobile Home Servicer','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 40,'Lloyd','Fani','lloyd.fani@zev.ru','(467) 487-7239','1991-03-29','Floor Refinisher','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 41,'Maud','Dunn','maud.dunn@nabeaga.ni','(724) 340-3634','1954-06-20','Senior Sales Associate','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 42,'Henry','Gigli','henry.gigli@kaot.ps','(413) 229-8428','1987-08-23','Tile Designer','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 43,'Virgie','Werner','virgie.werner@tawuctuj.cf','(886) 292-9749','1940-10-01','Econometrics Professor','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 44,'Gregory','Cozzi','gregory.cozzi@eh.ru','(418) 472-1239','1993-07-25','Basketball Player','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 45,'Lucinda','Gil','lucinda.gil@fajjusuz.kr','(961) 233-3461','1933-07-16','Indirect Fire Infantryman','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 46,'Gertrude','Verbeek','gertrude.verbeek@pave.cc','(605) 226-4037','1963-07-30','Licensed Esthetician','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 47,'Mattie','Graham','mattie.graham@ispaviw.gt','(719) 765-1705','1956-05-27','Antisubmarine Warfare Intelligence Officer','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 48,'Bryan','Shaw','bryan.shaw@ha.ee','(232) 228-5539','2018-01-21','Research Assistant','Manager',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 49,'Essie','Adams','essie.adams@iliat.cw','(768) 554-8377','1957-08-02','Cigar Roller','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 50,'Gary','Osborne','gary.osborne@do.ga','(311) 731-7079','2008-05-21','Customer Support Representative','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 51,'Richard','Silva','richard.silva@wi.lc','(207) 554-6244','2013-12-31','Programmer','Manager',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 52,'Dustin','Pestelli','dustin.pestelli@iwage.la','(558) 913-2855','1977-05-06','Global Engineering Manager','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 53,'Henrietta','Hilton','henrietta.hilton@joopoju.pn','(832) 759-6654','1943-02-28','Telegraph and Teletype Operator','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 54,'Francisco','Giordano','francisco.giordano@gojawu.tn','(482) 736-8079','1987-08-07','Hairpiece Stylist','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 55,'Cynthia','Sardi','cynthia.sardi@afigoh.mm','(677) 345-2680','1973-01-25','Tobacco Buyer','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 56,'Lula','Testi','lula.testi@benom.tj','(610) 374-7581','1970-11-22','Marine Steamfitter','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 57,'Bess','Lucas','bess.lucas@jevakbe.cd','(982) 583-8067','1928-05-02','Attending Anesthesiologist','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 58,'Linnie','Driessen','linnie.driessen@darhow.tr','(680) 266-3167','1967-01-31','Certified Indoor Environmentalist','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 59,'Eva','Tesi','eva.tesi@dupid.cf','(611) 955-4652','1970-12-13','Land Management Forester','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 60,'Augusta','Sakai','augusta.sakai@comouc.ee','(940) 714-8088','1935-09-20','Digital Proofing and Platemaker','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 61,'Mathilda','Schwarz','mathilda.schwarz@igunisi.ao','(868) 481-5125','1941-01-13','Public Health Veterinarian','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 62,'Joe','Riley','joe.riley@pe.vu','(225) 395-2772','2016-06-23','Statement Processor','External',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 63,'Leon','McGee','leon.mcgee@puk.se','(365) 837-6888','2010-04-09','Computer Applications Developer','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 64,'Florence','Viviani','florence.viviani@vegub.no','(606) 352-8734','1969-01-30','African History Professor','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 65,'Lee','Miceli','lee.miceli@rucwi.pf','(555) 800-7339','1981-05-05','Gastroenterology Professor','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 66,'Celia','Sodi','celia.sodi@agijit.iq','(657) 357-3671','1972-02-26','Laboratory Animal Caretaker','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 67,'Aaron','Misuri','aaron.misuri@loolu.lu','(523) 789-5485','1981-01-27','Water Pump Installer','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 68,'Fanny','Parkinson','fanny.parkinson@tupwovali.cw','(766) 966-7387','1948-11-08','Orthopedic Cast Specialist','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 69,'Phoebe','Vitale','phoebe.vitale@hidge.fo','(672) 613-2954','1969-03-11','Budget Coordinator','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 70,'Edith','Brennan','edith.brennan@liowci.ir','(803) 549-9387','1947-08-21','Railroad Engineer','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 71,'Jeremy','Marilli','jeremy.marilli@vesa.pf','(526) 435-1819','1983-02-23','Chief Projectionist','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 72,'Kathryn','Huet','kathryn.huet@wupikdoh.by','(937) 855-5936','1926-08-12','Telecasting Engineer','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 73,'Lelia','Matsuo','lelia.matsuo@dajsiphaj.az','(960) 335-6192','1934-08-23','Drama Therapist','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 74,'Virginia','Woods','virginia.woods@soofpe.ht','(735) 809-2611','1954-05-31','General Superintendent','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 75,'Sally','Aoki','sally.aoki@aruzusjas.tc','(857) 797-7918','1936-08-01','Technical Communicator','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 76,'Isabelle','de Ridder','isabelle.deridder@ufeco.in','(659) 331-1543','1962-05-18','Leisure Studies Professor','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 77,'Rosie','Murphy','rosie.murphy@uneehi.id','(759) 639-8597','1957-11-18','Air Conditioning Service Technician','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 78,'Lou','Meyer','lou.meyer@hahinaba.gm','(942) 352-4854','1928-08-13','Business Unit Manager','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 79,'Rodney','Love','rodney.love@zun.ph','(247) 867-8287','2011-12-08','Job Estimator','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 80,'Kenneth','Bianchini','kenneth.bianchini@jo.ws','(302) 793-9936','2000-11-29','Correctional Officer Sergeant','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 81,'Essie','Dietrich','essie.dietrich@goltuefo.mn','(861) 740-6628','1938-08-01','Parking Meter Collector','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 82,'Leila','Simon','leila.simon@lupuwuzo.gw','(953) 866-9992','1930-04-28','Signals Intelligence/Electronic Warfare Chief','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 83,'Eva','Pierre','eva.pierre@reduzris.ee','(915) 491-8384','1927-05-10','Clinical Psychiatrist','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 84,'Landon','Moretti','landon.moretti@pubsav.sk','(584) 909-6235','1980-08-12','Wildlife Officer','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 85,'Mittie','Sardi','mittie.sardi@lullip.nf','(673) 849-4256','1973-01-20','Food Chemist','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 86,'Corey','McDaniel','corey.mcdaniel@aba.tc','(268) 208-9643','2012-03-26','Advanced Foreign Counterintelligence Specialist (Afcs)','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 87,'Hester','Stein','hester.stein@kettujwo.eu','(873) 489-6641','1939-01-17','Forest Fire Officer','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 88,'Danny','Lowe','danny.lowe@ju.sd','(243) 974-5539','2013-05-01','Catalogue Illustrator','External',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 89,'Lillie','Winter','lillie.winter@vioburez.vi','(816) 699-1291','1945-03-26','Knife Grinder','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 90,'Brandon','Borchi','brandon.borchi@ig.al','(319) 401-1090','2000-01-16','Neuropsychiatrist','Supervisor',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 91,'Isaac','Bernardi','isaac.bernardi@omu.bj','(359) 691-6408','2001-06-28','Bottle Packer','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 92,'Clyde','Crawford','clyde.crawford@luw.dz','(273) 892-4646','2018-07-01','Special Education Kindergarten Teacher','External',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 93,'Paul','Sherman','paul.sherman@pi.cf','(304) 610-2881','2007-12-08','Commercial Art Instructor','Worker',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 94,'Craig','Russell','craig.russell@zu.nz','(237) 969-2900','2019-10-05','Ferryboat Captain','Supervisor',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 95,'John','Sutton','john.sutton@ag.ee','(207) 424-6468','2012-12-16','School Social Worker','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 96,'Francisco','Formigli','francisco.formigli@fopav.tn','(481) 661-8179','1989-11-30','Joint Terminal Attack Controller','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 97,'Gary','Baker','gary.baker@ji.cf','(212) 510-3444','2021-12-20','VP Sales','Worker',true)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 98,'Earl','Giovannoni','earl.giovannoni@lojet.ge','(433) 862-3076','1987-04-30','Auto Service Station Attendant','Manager',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 99,'Helen','Zanieri','helen.zanieri@ukve.tn','(619) 506-4452','1968-09-11','Healthcare Social Worker','External',false)
insert into sample_person(version, id,first_name,last_name,email,phone,date_of_birth,occupation,role,important) values (1, 100,'Agnes','Toccafondi','agnes.toccafondi@viipo.ae','(616) 688-6883','1970-10-01','Comedian','External',false)
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 1,'697','Lane','Insurance Clerk')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 2,'107','Rodriquez','Mortarman')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 3,'507','Selvi','Beer Coil Cleaner')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 4,'106','Miles','Scale Attendant')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 5,'524','Tesi','Clinical Audiologist')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 6,'867','Ishii','Parking Meter Collector')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 7,'571','Jacobs','Business Unit Manager')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 8,'142','Goodman','Technical Communicator')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 9,'651','Bennett','Correctional Officer Sergeant')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 10,'781','Leach','Food Chemist')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 11,'420','Miccinesi','Signals Intelligence/Electronic Warfare Chief')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 12,'812','Parkes','Language Pathologist')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 13,'662','Gray','Wildlife Officer')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 14,'154','Stokes','Bindery Machine Operator')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 15,'944','Matthieu','Instructional Aide')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 16,'750','Rhodes','Clinical Psychiatrist')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 17,'491','Romoli','Mortician Investigator')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 18,'748','Holden','Rod Buster Helper')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 19,'918','Montero','Classroom Aide')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 20,'903','Molina','Traditional Chinese Herbalist')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 21,'738','Todd','Electronic Drafter')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 22,'94','Pearson','Vault Teller')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 23,'284','Ciappi','Fire Sprinkler Installer')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 24,'499','Salucci','Brewery Pumper')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 25,'367','Grossi','Kitchen Chef')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 26,'576','Koopmans','Medical Esthetician')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 27,'882','Fujimoto','Auto Tire Worker')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 28,'909','Vidal','Semi-Truck Driver')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 29,'770','Henry','Command And Control')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 30,'949','Brun','Drywall Hanger')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 31,'148','Blake','Real Property Evaluator')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 32,'508','Serafini','Human Performance Professor')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 33,'653','Carter','V/Stol Landing Signal Officer')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 34,'314','Fabbrini','Air Control/Anti-Air Warfare Officer')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 35,'798','Turnbull','General Superintendent')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 36,'97','Hopkins','Child Protective Services Social Worker')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 37,'789','Lyons','Lens Grinder and Polisher')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 38,'834','Weiß','Civil Engineering Professor')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 39,'941','Gauthier','Mobile Home Servicer')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 40,'322','Fani','Floor Refinisher')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 41,'689','Dunn','Senior Sales Associate')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 42,'357','Gigli','Tile Designer')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 43,'827','Werner','Econometrics Professor')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 44,'298','Cozzi','Basketball Player')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 45,'899','Gil','Indirect Fire Infantryman')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 46,'598','Verbeek','Licensed Esthetician')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 47,'670','Graham','Antisubmarine Warfare Intelligence Officer')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 48,'53','Shaw','Research Assistant')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 49,'658','Adams','Cigar Roller')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 50,'150','Osborne','Customer Support Representative')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 51,'94','Silva','Programmer')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 52,'461','Pestelli','Global Engineering Manager')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 53,'803','Hilton','Telegraph and Teletype Operator')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 54,'358','Giordano','Hairpiece Stylist')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 55,'503','Sardi','Tobacco Buyer')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 56,'525','Testi','Marine Steamfitter')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 57,'951','Lucas','Attending Anesthesiologist')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 58,'563','Driessen','Certified Indoor Environmentalist')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 59,'525','Tesi','Land Management Forester')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 60,'877','Sakai','Digital Proofing and Platemaker')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 61,'824','Schwarz','Public Health Veterinarian')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 62,'69','Riley','Statement Processor')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 63,'131','McGee','Computer Applications Developer')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 64,'543','Viviani','African History Professor')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 65,'421','Miceli','Gastroenterology Professor')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 66,'512','Sodi','Laboratory Animal Caretaker')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 67,'423','Misuri','Water Pump Installer')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 68,'746','Parkinson','Orthopedic Cast Specialist')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 69,'542','Vitale','Budget Coordinator')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 70,'758','Brennan','Railroad Engineer')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 71,'402','Marilli','Chief Projectionist')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 72,'968','Huet','Telecasting Engineer')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 73,'888','Matsuo','Drama Therapist')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 74,'690','Woods','General Superintendent')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 75,'868','Aoki','Technical Communicator')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 76,'610','de Ridder','Leisure Studies Professor')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 77,'655','Murphy','Air Conditioning Service Technician')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 78,'948','Meyer','Business Unit Manager')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 79,'114','Love','Job Estimator')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 80,'225','Bianchini','Correctional Officer Sergeant')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 81,'848','Dietrich','Parking Meter Collector')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 82,'931','Simon','Signals Intelligence/Electronic Warfare Chief')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 83,'961','Pierre','Clinical Psychiatrist')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 84,'428','Moretti','Wildlife Officer')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 85,'503','Sardi','Food Chemist')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 86,'111','McDaniel','Advanced Foreign Counterintelligence Specialist (Afcs)')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 87,'844','Stein','Forest Fire Officer')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 88,'100','Lowe','Catalogue Illustrator')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 89,'782','Winter','Knife Grinder')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 90,'233','Borchi','Neuropsychiatrist')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 91,'219','Bernardi','Bottle Packer')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 92,'49','Crawford','Special Education Kindergarten Teacher')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 93,'154','Sherman','Commercial Art Instructor')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 94,'36','Russell','Ferryboat Captain')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 95,'104','Sutton','School Social Worker')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 96,'335','Formigli','Joint Terminal Attack Controller')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 97,'14','Baker','VP Sales')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 98,'361','Giovannoni','Auto Service Station Attendant')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 99,'547','Zanieri','Healthcare Social Worker')
insert into configuration_parameters(version, id,parameter_id,parameter_name,value) values (1, 100,'527','Toccafondi','Comedian')
